name: deploy

# 代码提交到main分支时触发github action
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest                                      # 在什么环境执行
    steps:                                                      # 步骤
        - name: Checkout                                        # 第一步 Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Setup Hugo                                      # 第二步 Hugo 配置
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: '0.144.2'                           # 使用的 Hugo 版本
              extended: true                                    # 是否使用 extended 版本

        - name: Build Web                                       # 第三步 构建
          run: hugo -E                                          # 构建命令

        - name: Deploy Web                                      # 第四步 发布
          uses: peaceiris/actions-gh-pages@v4
          with:
              PERSONAL_TOKEN: ${{ secrets.你的KEY名称 }}
              EXTERNAL_REPOSITORY: 你的Github帐号/你的Github帐号.github.io
              PUBLISH_BRANCH: main
              PUBLISH_DIR: ./public
              commit_message: auto deploy
